version: 3
services:
  app:
    type: nodejs
    buildPack: bun
    build:
      command: bun install && bun run build
      output: .output
    start:
      command: bun x vinxi start
    environment:
      - NODE_ENV=production
      - VITE_DISABLE_SOURCEMAPS=true
      - VINXI_DISABLE_SOURCEMAPS=true
      - DISABLE_EXTRACTION=true
