version: 3
services:
  app:
    type: static
    buildPack: docker
    build:
      dockerfile: Dockerfile
      output: .output/public
    staticConfig:
      engine: nginx
      headers:
        - name: Cache-Control
          value: no-cache
      spa: true
