version: 3
services:
  app:
    type: static
    buildPack: nixpacks
    build:
      command: |
        bun install && \
        NODE_ENV=production \
        VITE_DISABLE_SOURCEMAPS=true \
        VINXI_DISABLE_SOURCEMAPS=true \
        DISABLE_EXTRACTION=true \
        bun run build
      output: dist
    staticConfig:
      engine: nginx
      headers:
        - name: Cache-Control
          value: no-cache
      spa: true
