version: 3
services:
  app:
    build:
      cache:
        enabled: true
        # Specify cache mount points
        mounts:
          - type: cache
            target: /root/.bun
          - type: cache
            target: /app/node_modules
          - type: cache
            target: /app/.vinxi
          - type: cache
            target: /app/.output
      command: NODE_ENV=production bun x vinxi build
      environment:
        - NODE_ENV=production
    # ... rest of config
