version: 3
services:
  app:
    type: static
    buildPack: bun
    build:
      command: |
        bun install && \
        NODE_ENV=production \
        VITE_DISABLE_SOURCEMAPS=true \
        VINXI_DISABLE_SOURCEMAPS=true \
        DISABLE_EXTRACTION=true \
        bun run build && \
        cp -r .output/public/* /usr/share/nginx/html/
      output: .output/public
    staticConfig:
      engine: nginx
      headers:
        - name: Cache-Control
          value: no-cache
      spa: true
