[phases.setup]
nixPkgs = ['nodejs_20', 'bun']
nixLibs = ['libuuid', 'libGL']
aptPkgs = ['curl', 'wget']

[phases.install]
cmds = [
  'bun i --frozen-lockfile --no-save'
]
cacheDirectories = [
  '/root/.bun',
  'node_modules/.cache',
  '.vinxi',
  '.output'
]

[phases.build]
cmds = [
  'NODE_ENV=production VITE_DISABLE_SOURCEMAPS=true VINXI_DISABLE_SOURCEMAPS=true DISABLE_EXTRACTION=true bun x vinxi build'
]

[start]
cmd = 'NODE_ENV=production bun x vinxi start' 