[phases.build]
cmds = [
  "rm -rf app.config.timestamp_*",
  "export PATH=/app/node_modules/.bin:$PATH",
  "vinxi build"
]
cacheDirectories = [
  'node_modules/.cache',
  '.vinxi',
  'dist',
  '.output'
]

[phases.install]
cmds = [
  'bun i --no-save',
  'ln -s /app/node_modules/.bin/* /usr/local/bin/'
]
cacheDirectories = [
  '/root/.bun',
  'node_modules',
  '.vinxi/build'
]

[phases.setup]
nixPkgs = [
  'nodejs_18',
  'bun',
  'coreutils'
]
nixLibs = [
  'libuuid',
  'libGL'
]

[start]
cmd = "vinxi start"
  