[phases.setup]
nixPkgs = ['nodejs_18', 'bun']
nixLibs = ['libuuid', 'libGL']
nixOverlays = ['https://github.com/railwayapp/nix-npm-overlay/archive/main.tar.gz']

[phases.install]
cmds = [
  'bun i --frozen-lockfile',
  'bun x vinxi --version'
]

[phases.build]
cmds = ['NODE_ENV=production bun x vinxi build']

[start]
cmd = 'NODE_ENV=production bun x vinxi start' 