/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LyricsImport } from './routes/_lyrics'
import { Route as AppImport } from './routes/_app'
import { Route as gamepadImport } from './routes/@gamepad'
import { Route as UsernameImport } from './routes/$username'
import { Route as AppIndexImport } from './routes/_app/index'
import { Route as AppWidgetsImport } from './routes/_app/widgets'
import { Route as AppTestImport } from './routes/_app/test'
import { Route as AppPostsImport } from './routes/_app/posts'
import { Route as AppAuthedImport } from './routes/_app/_authed'
import { Route as usernameGamepadImport } from './routes/[username].gamepad'
import { Route as UsernameOverlayImport } from './routes/$username/overlay'
import { Route as UsernameLyricsImport } from './routes/$username/lyrics'
import { Route as LyricsLyricsIndexImport } from './routes/_lyrics/lyrics.index'
import { Route as AppWidgetsIndexImport } from './routes/_app/widgets/index'
import { Route as AppWheelspinIndexImport } from './routes/_app/wheelspin/index'
import { Route as AppTeampickerIndexImport } from './routes/_app/teampicker/index'
import { Route as AppPricingIndexImport } from './routes/_app/pricing/index'
import { Route as AppWidgetsVisualizerImport } from './routes/_app/widgets/visualizer'
import { Route as AppWidgetsStatsImport } from './routes/_app/widgets/stats'
import { Route as AppWidgetsOverlayImport } from './routes/_app/widgets/overlay'
import { Route as AppWidgetsLyricsImport } from './routes/_app/widgets/lyrics'
import { Route as AppWidgetsGamepadImport } from './routes/_app/widgets/gamepad'
import { Route as AppWidgetsChatImport } from './routes/_app/widgets/chat'
import { Route as AppWidgetsAlertsImport } from './routes/_app/widgets/alerts'
import { Route as AppTeampickerBracketIdImport } from './routes/_app/teampicker/$bracketId'
import { Route as AppSignUpSplatImport } from './routes/_app/sign-up.$'
import { Route as AppSignInSplatImport } from './routes/_app/sign-in.$'
import { Route as AppPostsPostIdImport } from './routes/_app/posts.$postId'
import { Route as AppCheckoutSuccessImport } from './routes/_app/checkout.success'
import { Route as AppCheckoutProductIdImport } from './routes/_app/checkout.$productId'
import { Route as AppAuthedDashboardImport } from './routes/_app/_authed/dashboard'
import { Route as AppPostsPostIdDeepImport } from './routes/_app/posts_.$postId.deep'
import { Route as AppDashboardWidgetsVisualizerImport } from './routes/_app/dashboard/widgets/visualizer'
import { Route as AppDashboardWidgetsGamepadImport } from './routes/_app/dashboard/widgets/gamepad'
import { Route as AppDashboardWidgetsDevImport } from './routes/_app/dashboard/widgets/dev'

// Create/Update Routes

const LyricsRoute = LyricsImport.update({
  id: '/_lyrics',
  getParentRoute: () => rootRoute,
} as any)

const AppRoute = AppImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const gamepadRoute = gamepadImport.update({
  id: '/@gamepad',
  path: '/@gamepad',
  getParentRoute: () => rootRoute,
} as any)

const UsernameRoute = UsernameImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => rootRoute,
} as any)

const AppIndexRoute = AppIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)

const AppWidgetsRoute = AppWidgetsImport.update({
  id: '/widgets',
  path: '/widgets',
  getParentRoute: () => AppRoute,
} as any)

const AppTestRoute = AppTestImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => AppRoute,
} as any)

const AppPostsRoute = AppPostsImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AppRoute,
} as any)

const AppAuthedRoute = AppAuthedImport.update({
  id: '/_authed',
  getParentRoute: () => AppRoute,
} as any)

const usernameGamepadRoute = usernameGamepadImport.update({
  id: '/[username]/gamepad',
  path: '/[username]/gamepad',
  getParentRoute: () => rootRoute,
} as any)

const UsernameOverlayRoute = UsernameOverlayImport.update({
  id: '/overlay',
  path: '/overlay',
  getParentRoute: () => UsernameRoute,
} as any)

const UsernameLyricsRoute = UsernameLyricsImport.update({
  id: '/lyrics',
  path: '/lyrics',
  getParentRoute: () => UsernameRoute,
} as any)

const LyricsLyricsIndexRoute = LyricsLyricsIndexImport.update({
  id: '/lyrics/',
  path: '/lyrics/',
  getParentRoute: () => LyricsRoute,
} as any)

const AppWidgetsIndexRoute = AppWidgetsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppWidgetsRoute,
} as any)

const AppWheelspinIndexRoute = AppWheelspinIndexImport.update({
  id: '/wheelspin/',
  path: '/wheelspin/',
  getParentRoute: () => AppRoute,
} as any)

const AppTeampickerIndexRoute = AppTeampickerIndexImport.update({
  id: '/teampicker/',
  path: '/teampicker/',
  getParentRoute: () => AppRoute,
} as any)

const AppPricingIndexRoute = AppPricingIndexImport.update({
  id: '/pricing/',
  path: '/pricing/',
  getParentRoute: () => AppRoute,
} as any)

const AppWidgetsVisualizerRoute = AppWidgetsVisualizerImport.update({
  id: '/visualizer',
  path: '/visualizer',
  getParentRoute: () => AppWidgetsRoute,
} as any)

const AppWidgetsStatsRoute = AppWidgetsStatsImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AppWidgetsRoute,
} as any)

const AppWidgetsOverlayRoute = AppWidgetsOverlayImport.update({
  id: '/overlay',
  path: '/overlay',
  getParentRoute: () => AppWidgetsRoute,
} as any)

const AppWidgetsLyricsRoute = AppWidgetsLyricsImport.update({
  id: '/lyrics',
  path: '/lyrics',
  getParentRoute: () => AppWidgetsRoute,
} as any)

const AppWidgetsGamepadRoute = AppWidgetsGamepadImport.update({
  id: '/gamepad',
  path: '/gamepad',
  getParentRoute: () => AppWidgetsRoute,
} as any)

const AppWidgetsChatRoute = AppWidgetsChatImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppWidgetsRoute,
} as any)

const AppWidgetsAlertsRoute = AppWidgetsAlertsImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppWidgetsRoute,
} as any)

const AppTeampickerBracketIdRoute = AppTeampickerBracketIdImport.update({
  id: '/teampicker/$bracketId',
  path: '/teampicker/$bracketId',
  getParentRoute: () => AppRoute,
} as any)

const AppSignUpSplatRoute = AppSignUpSplatImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => AppRoute,
} as any)

const AppSignInSplatRoute = AppSignInSplatImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => AppRoute,
} as any)

const AppPostsPostIdRoute = AppPostsPostIdImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => AppPostsRoute,
} as any)

const AppCheckoutSuccessRoute = AppCheckoutSuccessImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => AppRoute,
} as any)

const AppCheckoutProductIdRoute = AppCheckoutProductIdImport.update({
  id: '/checkout/$productId',
  path: '/checkout/$productId',
  getParentRoute: () => AppRoute,
} as any)

const AppAuthedDashboardRoute = AppAuthedDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppAuthedRoute,
} as any)

const AppPostsPostIdDeepRoute = AppPostsPostIdDeepImport.update({
  id: '/posts_/$postId/deep',
  path: '/posts/$postId/deep',
  getParentRoute: () => AppRoute,
} as any)

const AppDashboardWidgetsVisualizerRoute =
  AppDashboardWidgetsVisualizerImport.update({
    id: '/dashboard/widgets/visualizer',
    path: '/dashboard/widgets/visualizer',
    getParentRoute: () => AppRoute,
  } as any)

const AppDashboardWidgetsGamepadRoute = AppDashboardWidgetsGamepadImport.update(
  {
    id: '/dashboard/widgets/gamepad',
    path: '/dashboard/widgets/gamepad',
    getParentRoute: () => AppRoute,
  } as any,
)

const AppDashboardWidgetsDevRoute = AppDashboardWidgetsDevImport.update({
  id: '/dashboard/widgets/dev',
  path: '/dashboard/widgets/dev',
  getParentRoute: () => AppRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$username': {
      id: '/$username'
      path: '/$username'
      fullPath: '/$username'
      preLoaderRoute: typeof UsernameImport
      parentRoute: typeof rootRoute
    }
    '/@gamepad': {
      id: '/@gamepad'
      path: '/@gamepad'
      fullPath: '/@gamepad'
      preLoaderRoute: typeof gamepadImport
      parentRoute: typeof rootRoute
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/_lyrics': {
      id: '/_lyrics'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LyricsImport
      parentRoute: typeof rootRoute
    }
    '/$username/lyrics': {
      id: '/$username/lyrics'
      path: '/lyrics'
      fullPath: '/$username/lyrics'
      preLoaderRoute: typeof UsernameLyricsImport
      parentRoute: typeof UsernameImport
    }
    '/$username/overlay': {
      id: '/$username/overlay'
      path: '/overlay'
      fullPath: '/$username/overlay'
      preLoaderRoute: typeof UsernameOverlayImport
      parentRoute: typeof UsernameImport
    }
    '/[username]/gamepad': {
      id: '/[username]/gamepad'
      path: '/[username]/gamepad'
      fullPath: '/[username]/gamepad'
      preLoaderRoute: typeof usernameGamepadImport
      parentRoute: typeof rootRoute
    }
    '/_app/_authed': {
      id: '/_app/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppAuthedImport
      parentRoute: typeof AppImport
    }
    '/_app/posts': {
      id: '/_app/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof AppPostsImport
      parentRoute: typeof AppImport
    }
    '/_app/test': {
      id: '/_app/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof AppTestImport
      parentRoute: typeof AppImport
    }
    '/_app/widgets': {
      id: '/_app/widgets'
      path: '/widgets'
      fullPath: '/widgets'
      preLoaderRoute: typeof AppWidgetsImport
      parentRoute: typeof AppImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/_authed/dashboard': {
      id: '/_app/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppAuthedDashboardImport
      parentRoute: typeof AppAuthedImport
    }
    '/_app/checkout/$productId': {
      id: '/_app/checkout/$productId'
      path: '/checkout/$productId'
      fullPath: '/checkout/$productId'
      preLoaderRoute: typeof AppCheckoutProductIdImport
      parentRoute: typeof AppImport
    }
    '/_app/checkout/success': {
      id: '/_app/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof AppCheckoutSuccessImport
      parentRoute: typeof AppImport
    }
    '/_app/posts/$postId': {
      id: '/_app/posts/$postId'
      path: '/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof AppPostsPostIdImport
      parentRoute: typeof AppPostsImport
    }
    '/_app/sign-in/$': {
      id: '/_app/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof AppSignInSplatImport
      parentRoute: typeof AppImport
    }
    '/_app/sign-up/$': {
      id: '/_app/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof AppSignUpSplatImport
      parentRoute: typeof AppImport
    }
    '/_app/teampicker/$bracketId': {
      id: '/_app/teampicker/$bracketId'
      path: '/teampicker/$bracketId'
      fullPath: '/teampicker/$bracketId'
      preLoaderRoute: typeof AppTeampickerBracketIdImport
      parentRoute: typeof AppImport
    }
    '/_app/widgets/alerts': {
      id: '/_app/widgets/alerts'
      path: '/alerts'
      fullPath: '/widgets/alerts'
      preLoaderRoute: typeof AppWidgetsAlertsImport
      parentRoute: typeof AppWidgetsImport
    }
    '/_app/widgets/chat': {
      id: '/_app/widgets/chat'
      path: '/chat'
      fullPath: '/widgets/chat'
      preLoaderRoute: typeof AppWidgetsChatImport
      parentRoute: typeof AppWidgetsImport
    }
    '/_app/widgets/gamepad': {
      id: '/_app/widgets/gamepad'
      path: '/gamepad'
      fullPath: '/widgets/gamepad'
      preLoaderRoute: typeof AppWidgetsGamepadImport
      parentRoute: typeof AppWidgetsImport
    }
    '/_app/widgets/lyrics': {
      id: '/_app/widgets/lyrics'
      path: '/lyrics'
      fullPath: '/widgets/lyrics'
      preLoaderRoute: typeof AppWidgetsLyricsImport
      parentRoute: typeof AppWidgetsImport
    }
    '/_app/widgets/overlay': {
      id: '/_app/widgets/overlay'
      path: '/overlay'
      fullPath: '/widgets/overlay'
      preLoaderRoute: typeof AppWidgetsOverlayImport
      parentRoute: typeof AppWidgetsImport
    }
    '/_app/widgets/stats': {
      id: '/_app/widgets/stats'
      path: '/stats'
      fullPath: '/widgets/stats'
      preLoaderRoute: typeof AppWidgetsStatsImport
      parentRoute: typeof AppWidgetsImport
    }
    '/_app/widgets/visualizer': {
      id: '/_app/widgets/visualizer'
      path: '/visualizer'
      fullPath: '/widgets/visualizer'
      preLoaderRoute: typeof AppWidgetsVisualizerImport
      parentRoute: typeof AppWidgetsImport
    }
    '/_app/pricing/': {
      id: '/_app/pricing/'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof AppPricingIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/teampicker/': {
      id: '/_app/teampicker/'
      path: '/teampicker'
      fullPath: '/teampicker'
      preLoaderRoute: typeof AppTeampickerIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/wheelspin/': {
      id: '/_app/wheelspin/'
      path: '/wheelspin'
      fullPath: '/wheelspin'
      preLoaderRoute: typeof AppWheelspinIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/widgets/': {
      id: '/_app/widgets/'
      path: '/'
      fullPath: '/widgets/'
      preLoaderRoute: typeof AppWidgetsIndexImport
      parentRoute: typeof AppWidgetsImport
    }
    '/_lyrics/lyrics/': {
      id: '/_lyrics/lyrics/'
      path: '/lyrics'
      fullPath: '/lyrics'
      preLoaderRoute: typeof LyricsLyricsIndexImport
      parentRoute: typeof LyricsImport
    }
    '/_app/dashboard/widgets/dev': {
      id: '/_app/dashboard/widgets/dev'
      path: '/dashboard/widgets/dev'
      fullPath: '/dashboard/widgets/dev'
      preLoaderRoute: typeof AppDashboardWidgetsDevImport
      parentRoute: typeof AppImport
    }
    '/_app/dashboard/widgets/gamepad': {
      id: '/_app/dashboard/widgets/gamepad'
      path: '/dashboard/widgets/gamepad'
      fullPath: '/dashboard/widgets/gamepad'
      preLoaderRoute: typeof AppDashboardWidgetsGamepadImport
      parentRoute: typeof AppImport
    }
    '/_app/dashboard/widgets/visualizer': {
      id: '/_app/dashboard/widgets/visualizer'
      path: '/dashboard/widgets/visualizer'
      fullPath: '/dashboard/widgets/visualizer'
      preLoaderRoute: typeof AppDashboardWidgetsVisualizerImport
      parentRoute: typeof AppImport
    }
    '/_app/posts_/$postId/deep': {
      id: '/_app/posts_/$postId/deep'
      path: '/posts/$postId/deep'
      fullPath: '/posts/$postId/deep'
      preLoaderRoute: typeof AppPostsPostIdDeepImport
      parentRoute: typeof AppImport
    }
  }
}

// Create and export the route tree

interface UsernameRouteChildren {
  UsernameLyricsRoute: typeof UsernameLyricsRoute
  UsernameOverlayRoute: typeof UsernameOverlayRoute
}

const UsernameRouteChildren: UsernameRouteChildren = {
  UsernameLyricsRoute: UsernameLyricsRoute,
  UsernameOverlayRoute: UsernameOverlayRoute,
}

const UsernameRouteWithChildren = UsernameRoute._addFileChildren(
  UsernameRouteChildren,
)

interface AppAuthedRouteChildren {
  AppAuthedDashboardRoute: typeof AppAuthedDashboardRoute
}

const AppAuthedRouteChildren: AppAuthedRouteChildren = {
  AppAuthedDashboardRoute: AppAuthedDashboardRoute,
}

const AppAuthedRouteWithChildren = AppAuthedRoute._addFileChildren(
  AppAuthedRouteChildren,
)

interface AppPostsRouteChildren {
  AppPostsPostIdRoute: typeof AppPostsPostIdRoute
}

const AppPostsRouteChildren: AppPostsRouteChildren = {
  AppPostsPostIdRoute: AppPostsPostIdRoute,
}

const AppPostsRouteWithChildren = AppPostsRoute._addFileChildren(
  AppPostsRouteChildren,
)

interface AppWidgetsRouteChildren {
  AppWidgetsAlertsRoute: typeof AppWidgetsAlertsRoute
  AppWidgetsChatRoute: typeof AppWidgetsChatRoute
  AppWidgetsGamepadRoute: typeof AppWidgetsGamepadRoute
  AppWidgetsLyricsRoute: typeof AppWidgetsLyricsRoute
  AppWidgetsOverlayRoute: typeof AppWidgetsOverlayRoute
  AppWidgetsStatsRoute: typeof AppWidgetsStatsRoute
  AppWidgetsVisualizerRoute: typeof AppWidgetsVisualizerRoute
  AppWidgetsIndexRoute: typeof AppWidgetsIndexRoute
}

const AppWidgetsRouteChildren: AppWidgetsRouteChildren = {
  AppWidgetsAlertsRoute: AppWidgetsAlertsRoute,
  AppWidgetsChatRoute: AppWidgetsChatRoute,
  AppWidgetsGamepadRoute: AppWidgetsGamepadRoute,
  AppWidgetsLyricsRoute: AppWidgetsLyricsRoute,
  AppWidgetsOverlayRoute: AppWidgetsOverlayRoute,
  AppWidgetsStatsRoute: AppWidgetsStatsRoute,
  AppWidgetsVisualizerRoute: AppWidgetsVisualizerRoute,
  AppWidgetsIndexRoute: AppWidgetsIndexRoute,
}

const AppWidgetsRouteWithChildren = AppWidgetsRoute._addFileChildren(
  AppWidgetsRouteChildren,
)

interface AppRouteChildren {
  AppAuthedRoute: typeof AppAuthedRouteWithChildren
  AppPostsRoute: typeof AppPostsRouteWithChildren
  AppTestRoute: typeof AppTestRoute
  AppWidgetsRoute: typeof AppWidgetsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppCheckoutProductIdRoute: typeof AppCheckoutProductIdRoute
  AppCheckoutSuccessRoute: typeof AppCheckoutSuccessRoute
  AppSignInSplatRoute: typeof AppSignInSplatRoute
  AppSignUpSplatRoute: typeof AppSignUpSplatRoute
  AppTeampickerBracketIdRoute: typeof AppTeampickerBracketIdRoute
  AppPricingIndexRoute: typeof AppPricingIndexRoute
  AppTeampickerIndexRoute: typeof AppTeampickerIndexRoute
  AppWheelspinIndexRoute: typeof AppWheelspinIndexRoute
  AppDashboardWidgetsDevRoute: typeof AppDashboardWidgetsDevRoute
  AppDashboardWidgetsGamepadRoute: typeof AppDashboardWidgetsGamepadRoute
  AppDashboardWidgetsVisualizerRoute: typeof AppDashboardWidgetsVisualizerRoute
  AppPostsPostIdDeepRoute: typeof AppPostsPostIdDeepRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAuthedRoute: AppAuthedRouteWithChildren,
  AppPostsRoute: AppPostsRouteWithChildren,
  AppTestRoute: AppTestRoute,
  AppWidgetsRoute: AppWidgetsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppCheckoutProductIdRoute: AppCheckoutProductIdRoute,
  AppCheckoutSuccessRoute: AppCheckoutSuccessRoute,
  AppSignInSplatRoute: AppSignInSplatRoute,
  AppSignUpSplatRoute: AppSignUpSplatRoute,
  AppTeampickerBracketIdRoute: AppTeampickerBracketIdRoute,
  AppPricingIndexRoute: AppPricingIndexRoute,
  AppTeampickerIndexRoute: AppTeampickerIndexRoute,
  AppWheelspinIndexRoute: AppWheelspinIndexRoute,
  AppDashboardWidgetsDevRoute: AppDashboardWidgetsDevRoute,
  AppDashboardWidgetsGamepadRoute: AppDashboardWidgetsGamepadRoute,
  AppDashboardWidgetsVisualizerRoute: AppDashboardWidgetsVisualizerRoute,
  AppPostsPostIdDeepRoute: AppPostsPostIdDeepRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface LyricsRouteChildren {
  LyricsLyricsIndexRoute: typeof LyricsLyricsIndexRoute
}

const LyricsRouteChildren: LyricsRouteChildren = {
  LyricsLyricsIndexRoute: LyricsLyricsIndexRoute,
}

const LyricsRouteWithChildren =
  LyricsRoute._addFileChildren(LyricsRouteChildren)

export interface FileRoutesByFullPath {
  '/$username': typeof UsernameRouteWithChildren
  '/@gamepad': typeof gamepadRoute
  '': typeof AppAuthedRouteWithChildren
  '/$username/lyrics': typeof UsernameLyricsRoute
  '/$username/overlay': typeof UsernameOverlayRoute
  '/[username]/gamepad': typeof usernameGamepadRoute
  '/posts': typeof AppPostsRouteWithChildren
  '/test': typeof AppTestRoute
  '/widgets': typeof AppWidgetsRouteWithChildren
  '/': typeof AppIndexRoute
  '/dashboard': typeof AppAuthedDashboardRoute
  '/checkout/$productId': typeof AppCheckoutProductIdRoute
  '/checkout/success': typeof AppCheckoutSuccessRoute
  '/posts/$postId': typeof AppPostsPostIdRoute
  '/sign-in/$': typeof AppSignInSplatRoute
  '/sign-up/$': typeof AppSignUpSplatRoute
  '/teampicker/$bracketId': typeof AppTeampickerBracketIdRoute
  '/widgets/alerts': typeof AppWidgetsAlertsRoute
  '/widgets/chat': typeof AppWidgetsChatRoute
  '/widgets/gamepad': typeof AppWidgetsGamepadRoute
  '/widgets/lyrics': typeof AppWidgetsLyricsRoute
  '/widgets/overlay': typeof AppWidgetsOverlayRoute
  '/widgets/stats': typeof AppWidgetsStatsRoute
  '/widgets/visualizer': typeof AppWidgetsVisualizerRoute
  '/pricing': typeof AppPricingIndexRoute
  '/teampicker': typeof AppTeampickerIndexRoute
  '/wheelspin': typeof AppWheelspinIndexRoute
  '/widgets/': typeof AppWidgetsIndexRoute
  '/lyrics': typeof LyricsLyricsIndexRoute
  '/dashboard/widgets/dev': typeof AppDashboardWidgetsDevRoute
  '/dashboard/widgets/gamepad': typeof AppDashboardWidgetsGamepadRoute
  '/dashboard/widgets/visualizer': typeof AppDashboardWidgetsVisualizerRoute
  '/posts/$postId/deep': typeof AppPostsPostIdDeepRoute
}

export interface FileRoutesByTo {
  '/$username': typeof UsernameRouteWithChildren
  '/@gamepad': typeof gamepadRoute
  '': typeof AppAuthedRouteWithChildren
  '/$username/lyrics': typeof UsernameLyricsRoute
  '/$username/overlay': typeof UsernameOverlayRoute
  '/[username]/gamepad': typeof usernameGamepadRoute
  '/posts': typeof AppPostsRouteWithChildren
  '/test': typeof AppTestRoute
  '/': typeof AppIndexRoute
  '/dashboard': typeof AppAuthedDashboardRoute
  '/checkout/$productId': typeof AppCheckoutProductIdRoute
  '/checkout/success': typeof AppCheckoutSuccessRoute
  '/posts/$postId': typeof AppPostsPostIdRoute
  '/sign-in/$': typeof AppSignInSplatRoute
  '/sign-up/$': typeof AppSignUpSplatRoute
  '/teampicker/$bracketId': typeof AppTeampickerBracketIdRoute
  '/widgets/alerts': typeof AppWidgetsAlertsRoute
  '/widgets/chat': typeof AppWidgetsChatRoute
  '/widgets/gamepad': typeof AppWidgetsGamepadRoute
  '/widgets/lyrics': typeof AppWidgetsLyricsRoute
  '/widgets/overlay': typeof AppWidgetsOverlayRoute
  '/widgets/stats': typeof AppWidgetsStatsRoute
  '/widgets/visualizer': typeof AppWidgetsVisualizerRoute
  '/pricing': typeof AppPricingIndexRoute
  '/teampicker': typeof AppTeampickerIndexRoute
  '/wheelspin': typeof AppWheelspinIndexRoute
  '/widgets': typeof AppWidgetsIndexRoute
  '/lyrics': typeof LyricsLyricsIndexRoute
  '/dashboard/widgets/dev': typeof AppDashboardWidgetsDevRoute
  '/dashboard/widgets/gamepad': typeof AppDashboardWidgetsGamepadRoute
  '/dashboard/widgets/visualizer': typeof AppDashboardWidgetsVisualizerRoute
  '/posts/$postId/deep': typeof AppPostsPostIdDeepRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/$username': typeof UsernameRouteWithChildren
  '/@gamepad': typeof gamepadRoute
  '/_app': typeof AppRouteWithChildren
  '/_lyrics': typeof LyricsRouteWithChildren
  '/$username/lyrics': typeof UsernameLyricsRoute
  '/$username/overlay': typeof UsernameOverlayRoute
  '/[username]/gamepad': typeof usernameGamepadRoute
  '/_app/_authed': typeof AppAuthedRouteWithChildren
  '/_app/posts': typeof AppPostsRouteWithChildren
  '/_app/test': typeof AppTestRoute
  '/_app/widgets': typeof AppWidgetsRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/_authed/dashboard': typeof AppAuthedDashboardRoute
  '/_app/checkout/$productId': typeof AppCheckoutProductIdRoute
  '/_app/checkout/success': typeof AppCheckoutSuccessRoute
  '/_app/posts/$postId': typeof AppPostsPostIdRoute
  '/_app/sign-in/$': typeof AppSignInSplatRoute
  '/_app/sign-up/$': typeof AppSignUpSplatRoute
  '/_app/teampicker/$bracketId': typeof AppTeampickerBracketIdRoute
  '/_app/widgets/alerts': typeof AppWidgetsAlertsRoute
  '/_app/widgets/chat': typeof AppWidgetsChatRoute
  '/_app/widgets/gamepad': typeof AppWidgetsGamepadRoute
  '/_app/widgets/lyrics': typeof AppWidgetsLyricsRoute
  '/_app/widgets/overlay': typeof AppWidgetsOverlayRoute
  '/_app/widgets/stats': typeof AppWidgetsStatsRoute
  '/_app/widgets/visualizer': typeof AppWidgetsVisualizerRoute
  '/_app/pricing/': typeof AppPricingIndexRoute
  '/_app/teampicker/': typeof AppTeampickerIndexRoute
  '/_app/wheelspin/': typeof AppWheelspinIndexRoute
  '/_app/widgets/': typeof AppWidgetsIndexRoute
  '/_lyrics/lyrics/': typeof LyricsLyricsIndexRoute
  '/_app/dashboard/widgets/dev': typeof AppDashboardWidgetsDevRoute
  '/_app/dashboard/widgets/gamepad': typeof AppDashboardWidgetsGamepadRoute
  '/_app/dashboard/widgets/visualizer': typeof AppDashboardWidgetsVisualizerRoute
  '/_app/posts_/$postId/deep': typeof AppPostsPostIdDeepRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$username'
    | '/@gamepad'
    | ''
    | '/$username/lyrics'
    | '/$username/overlay'
    | '/[username]/gamepad'
    | '/posts'
    | '/test'
    | '/widgets'
    | '/'
    | '/dashboard'
    | '/checkout/$productId'
    | '/checkout/success'
    | '/posts/$postId'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/teampicker/$bracketId'
    | '/widgets/alerts'
    | '/widgets/chat'
    | '/widgets/gamepad'
    | '/widgets/lyrics'
    | '/widgets/overlay'
    | '/widgets/stats'
    | '/widgets/visualizer'
    | '/pricing'
    | '/teampicker'
    | '/wheelspin'
    | '/widgets/'
    | '/lyrics'
    | '/dashboard/widgets/dev'
    | '/dashboard/widgets/gamepad'
    | '/dashboard/widgets/visualizer'
    | '/posts/$postId/deep'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$username'
    | '/@gamepad'
    | ''
    | '/$username/lyrics'
    | '/$username/overlay'
    | '/[username]/gamepad'
    | '/posts'
    | '/test'
    | '/'
    | '/dashboard'
    | '/checkout/$productId'
    | '/checkout/success'
    | '/posts/$postId'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/teampicker/$bracketId'
    | '/widgets/alerts'
    | '/widgets/chat'
    | '/widgets/gamepad'
    | '/widgets/lyrics'
    | '/widgets/overlay'
    | '/widgets/stats'
    | '/widgets/visualizer'
    | '/pricing'
    | '/teampicker'
    | '/wheelspin'
    | '/widgets'
    | '/lyrics'
    | '/dashboard/widgets/dev'
    | '/dashboard/widgets/gamepad'
    | '/dashboard/widgets/visualizer'
    | '/posts/$postId/deep'
  id:
    | '__root__'
    | '/$username'
    | '/@gamepad'
    | '/_app'
    | '/_lyrics'
    | '/$username/lyrics'
    | '/$username/overlay'
    | '/[username]/gamepad'
    | '/_app/_authed'
    | '/_app/posts'
    | '/_app/test'
    | '/_app/widgets'
    | '/_app/'
    | '/_app/_authed/dashboard'
    | '/_app/checkout/$productId'
    | '/_app/checkout/success'
    | '/_app/posts/$postId'
    | '/_app/sign-in/$'
    | '/_app/sign-up/$'
    | '/_app/teampicker/$bracketId'
    | '/_app/widgets/alerts'
    | '/_app/widgets/chat'
    | '/_app/widgets/gamepad'
    | '/_app/widgets/lyrics'
    | '/_app/widgets/overlay'
    | '/_app/widgets/stats'
    | '/_app/widgets/visualizer'
    | '/_app/pricing/'
    | '/_app/teampicker/'
    | '/_app/wheelspin/'
    | '/_app/widgets/'
    | '/_lyrics/lyrics/'
    | '/_app/dashboard/widgets/dev'
    | '/_app/dashboard/widgets/gamepad'
    | '/_app/dashboard/widgets/visualizer'
    | '/_app/posts_/$postId/deep'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  UsernameRoute: typeof UsernameRouteWithChildren
  gamepadRoute: typeof gamepadRoute
  AppRoute: typeof AppRouteWithChildren
  LyricsRoute: typeof LyricsRouteWithChildren
  usernameGamepadRoute: typeof usernameGamepadRoute
}

const rootRouteChildren: RootRouteChildren = {
  UsernameRoute: UsernameRouteWithChildren,
  gamepadRoute: gamepadRoute,
  AppRoute: AppRouteWithChildren,
  LyricsRoute: LyricsRouteWithChildren,
  usernameGamepadRoute: usernameGamepadRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/$username",
        "/@gamepad",
        "/_app",
        "/_lyrics",
        "/[username]/gamepad"
      ]
    },
    "/$username": {
      "filePath": "$username.tsx",
      "children": [
        "/$username/lyrics",
        "/$username/overlay"
      ]
    },
    "/@gamepad": {
      "filePath": "@gamepad.tsx"
    },
    "/_app": {
      "filePath": "_app.tsx",
      "children": [
        "/_app/_authed",
        "/_app/posts",
        "/_app/test",
        "/_app/widgets",
        "/_app/",
        "/_app/checkout/$productId",
        "/_app/checkout/success",
        "/_app/sign-in/$",
        "/_app/sign-up/$",
        "/_app/teampicker/$bracketId",
        "/_app/pricing/",
        "/_app/teampicker/",
        "/_app/wheelspin/",
        "/_app/dashboard/widgets/dev",
        "/_app/dashboard/widgets/gamepad",
        "/_app/dashboard/widgets/visualizer",
        "/_app/posts_/$postId/deep"
      ]
    },
    "/_lyrics": {
      "filePath": "_lyrics.tsx",
      "children": [
        "/_lyrics/lyrics/"
      ]
    },
    "/$username/lyrics": {
      "filePath": "$username/lyrics.tsx",
      "parent": "/$username"
    },
    "/$username/overlay": {
      "filePath": "$username/overlay.tsx",
      "parent": "/$username"
    },
    "/[username]/gamepad": {
      "filePath": "[username].gamepad.tsx"
    },
    "/_app/_authed": {
      "filePath": "_app/_authed.tsx",
      "parent": "/_app",
      "children": [
        "/_app/_authed/dashboard"
      ]
    },
    "/_app/posts": {
      "filePath": "_app/posts.tsx",
      "parent": "/_app",
      "children": [
        "/_app/posts/$postId"
      ]
    },
    "/_app/test": {
      "filePath": "_app/test.tsx",
      "parent": "/_app"
    },
    "/_app/widgets": {
      "filePath": "_app/widgets.tsx",
      "parent": "/_app",
      "children": [
        "/_app/widgets/alerts",
        "/_app/widgets/chat",
        "/_app/widgets/gamepad",
        "/_app/widgets/lyrics",
        "/_app/widgets/overlay",
        "/_app/widgets/stats",
        "/_app/widgets/visualizer",
        "/_app/widgets/"
      ]
    },
    "/_app/": {
      "filePath": "_app/index.tsx",
      "parent": "/_app"
    },
    "/_app/_authed/dashboard": {
      "filePath": "_app/_authed/dashboard.tsx",
      "parent": "/_app/_authed"
    },
    "/_app/checkout/$productId": {
      "filePath": "_app/checkout.$productId.tsx",
      "parent": "/_app"
    },
    "/_app/checkout/success": {
      "filePath": "_app/checkout.success.tsx",
      "parent": "/_app"
    },
    "/_app/posts/$postId": {
      "filePath": "_app/posts.$postId.tsx",
      "parent": "/_app/posts"
    },
    "/_app/sign-in/$": {
      "filePath": "_app/sign-in.$.tsx",
      "parent": "/_app"
    },
    "/_app/sign-up/$": {
      "filePath": "_app/sign-up.$.tsx",
      "parent": "/_app"
    },
    "/_app/teampicker/$bracketId": {
      "filePath": "_app/teampicker/$bracketId.tsx",
      "parent": "/_app"
    },
    "/_app/widgets/alerts": {
      "filePath": "_app/widgets/alerts.tsx",
      "parent": "/_app/widgets"
    },
    "/_app/widgets/chat": {
      "filePath": "_app/widgets/chat.tsx",
      "parent": "/_app/widgets"
    },
    "/_app/widgets/gamepad": {
      "filePath": "_app/widgets/gamepad.tsx",
      "parent": "/_app/widgets"
    },
    "/_app/widgets/lyrics": {
      "filePath": "_app/widgets/lyrics.tsx",
      "parent": "/_app/widgets"
    },
    "/_app/widgets/overlay": {
      "filePath": "_app/widgets/overlay.tsx",
      "parent": "/_app/widgets"
    },
    "/_app/widgets/stats": {
      "filePath": "_app/widgets/stats.tsx",
      "parent": "/_app/widgets"
    },
    "/_app/widgets/visualizer": {
      "filePath": "_app/widgets/visualizer.tsx",
      "parent": "/_app/widgets"
    },
    "/_app/pricing/": {
      "filePath": "_app/pricing/index.tsx",
      "parent": "/_app"
    },
    "/_app/teampicker/": {
      "filePath": "_app/teampicker/index.tsx",
      "parent": "/_app"
    },
    "/_app/wheelspin/": {
      "filePath": "_app/wheelspin/index.tsx",
      "parent": "/_app"
    },
    "/_app/widgets/": {
      "filePath": "_app/widgets/index.tsx",
      "parent": "/_app/widgets"
    },
    "/_lyrics/lyrics/": {
      "filePath": "_lyrics/lyrics.index.tsx",
      "parent": "/_lyrics"
    },
    "/_app/dashboard/widgets/dev": {
      "filePath": "_app/dashboard/widgets/dev.tsx",
      "parent": "/_app"
    },
    "/_app/dashboard/widgets/gamepad": {
      "filePath": "_app/dashboard/widgets/gamepad.tsx",
      "parent": "/_app"
    },
    "/_app/dashboard/widgets/visualizer": {
      "filePath": "_app/dashboard/widgets/visualizer.tsx",
      "parent": "/_app"
    },
    "/_app/posts_/$postId/deep": {
      "filePath": "_app/posts_.$postId.deep.tsx",
      "parent": "/_app"
    }
  }
}
ROUTE_MANIFEST_END */
