import * as z from "zod";

export const commonSettingsSchema = z.object({
  backgroundColor: z.string().default("#ffffff"),
  fontColor: z.string().default("#000000"),
  fontFamily: z.string().default("sans-serif"),
  fontSize: z.number().min(8).max(120).default(16),
  fontWeight: z.string().default("400"),
  fontStyle: z.enum(["normal", "italic"]).default("normal"),
  underline: z.boolean().default(false),
  strikethrough: z.boolean().default(false),
  textAlignment: z.enum(["left", "center", "right", "justify"]).default("left"),
  lineHeight: z.number().min(0.5).max(3).default(1.8),
  letterSpacing: z.number().min(-5).max(10).default(0),
  wordSpacing: z.number().min(-10).max(10).default(0),
  borderColor: z.string().default("#000000"),
  borderTopWidth: z.number().min(0).max(20).default(0),
  borderRightWidth: z.number().min(0).max(20).default(0),
  borderBottomWidth: z.number().min(0).max(20).default(0),
  borderLeftWidth: z.number().min(0).max(20).default(0),
  borderStyle: z.enum(["none", "solid", "dashed", "dotted"]).default("none"),
  borderRadius: z.number().min(0).max(100).default(0),
  paddingTop: z.number().min(0).max(100).default(0),
  paddingRight: z.number().min(0).max(100).default(0),
  paddingBottom: z.number().min(0).max(100).default(0),
  paddingLeft: z.number().min(0).max(100).default(0),
  gap: z.number().min(0).max(100).default(0),
  matchArtworkColors: z.boolean().default(false),
  matchArtworkOpacity: z.number().min(0).max(1).default(0.5),
  textTransform: z
    .enum(["none", "capitalize", "uppercase", "lowercase"])
    .default("none"),
  textShadowColor: z.string().default("rgba(0, 0, 0, 0.5)"),
  textShadowHorizontal: z.number().default(0),
  textShadowVertical: z.number().default(0),
  textShadowBlur: z.number().default(0),
  canvasEnabled: z.boolean().default(false),
  albumCanvas: z.boolean().default(false),
  backgroundCanvas: z.boolean().default(false),
  backgroundCanvasOpacity: z.number().min(0).max(1).default(0.5),
  hideOnDisabled: z.boolean().default(false),
  pauseEnabled: z.boolean().default(false),
});

export type CommonSettings = z.infer<typeof commonSettingsSchema>;
